sonar.projectKey=MuhammadQasimTanveer_cohort-9-mern-11914-qasim
sonar.organization=MuhammadQasimTanveer
sonar.sources=frontend,backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**
sonar.sourceEncoding=UTF-8